<?php

/**
 * One gateway per carrier, its options from the environment (.env): a
 * gateway is configured only when every key under "needs" is set. Factory
 * names are the carriers' own; sandboxes are on unless <CARRIER>_SANDBOX=0.
 *
 * @return array<string, array{factory: string, needs: list<string>, options: array<string, mixed>}>
 */
$env = static fn (string $key, mixed $default = null): mixed => (false !== ($v = getenv($key)) && '' !== $v) ? $v : $default;
$sandbox = static fn (string $prefix): bool => '0' !== $env($prefix.'_SANDBOX', '1');
$rates = static fn (string $service, string $label, int $amount, string $currency = 'EUR'): array => [['service' => $service, 'label' => $label, 'currency' => $currency, 'bands' => [30000 => $amount]]];

return [
    'offline' => ['factory' => 'offline', 'needs' => [], 'options' => ['rates' => [['service' => 'pickup', 'label' => 'Click & collect', 'to_pickup_point' => true, 'bands' => [30000 => 0]]]]],
    'mondial_relay' => ['factory' => 'mondial_relay', 'needs' => [], 'options' => array_filter(['enseigne' => $env('MONDIAL_RELAY_ENSEIGNE'), 'private_key' => $env('MONDIAL_RELAY_PRIVATE_KEY'), 'sandbox' => null === $env('MONDIAL_RELAY_ENSEIGNE'), 'rates' => $rates('24R', 'Point relais', 490)])],
    'colissimo' => ['factory' => 'colissimo', 'needs' => [], 'options' => ['rates' => $rates('DOM', 'Colissimo domicile', 690)]],
    'chronopost' => ['factory' => 'chronopost', 'needs' => ['CHRONOPOST_ACCOUNT', 'CHRONOPOST_PASSWORD'], 'options' => ['account_number' => $env('CHRONOPOST_ACCOUNT'), 'password' => $env('CHRONOPOST_PASSWORD'), 'sub_account' => $env('CHRONOPOST_SUB_ACCOUNT')]],
    'ups' => ['factory' => 'ups', 'needs' => ['UPS_CLIENT_ID', 'UPS_CLIENT_SECRET', 'UPS_ACCOUNT'], 'options' => ['client_id' => $env('UPS_CLIENT_ID'), 'client_secret' => $env('UPS_CLIENT_SECRET'), 'account_number' => $env('UPS_ACCOUNT'), 'sandbox' => $sandbox('UPS')]],
    'fedex' => ['factory' => 'fedex', 'needs' => ['FEDEX_CLIENT_ID', 'FEDEX_CLIENT_SECRET', 'FEDEX_ACCOUNT'], 'options' => ['client_id' => $env('FEDEX_CLIENT_ID'), 'client_secret' => $env('FEDEX_CLIENT_SECRET'), 'account_number' => $env('FEDEX_ACCOUNT'), 'sandbox' => $sandbox('FEDEX')]],
    'dhl' => ['factory' => 'dhl', 'needs' => ['DHL_API_KEY', 'DHL_API_SECRET', 'DHL_ACCOUNT'], 'options' => ['api_key' => $env('DHL_API_KEY'), 'api_secret' => $env('DHL_API_SECRET'), 'account_number' => $env('DHL_ACCOUNT'), 'location_api_key' => $env('DHL_LOCATION_KEY'), 'sandbox' => $sandbox('DHL')]],
    'tnt' => ['factory' => 'tnt', 'needs' => ['TNT_USERNAME', 'TNT_PASSWORD', 'TNT_ACCOUNT'], 'options' => ['username' => $env('TNT_USERNAME'), 'password' => $env('TNT_PASSWORD'), 'account_number' => $env('TNT_ACCOUNT')]],
    'gls' => ['factory' => 'gls', 'needs' => ['GLS_USERNAME', 'GLS_PASSWORD', 'GLS_CONTACT_ID'], 'options' => ['username' => $env('GLS_USERNAME'), 'password' => $env('GLS_PASSWORD'), 'contact_id' => $env('GLS_CONTACT_ID'), 'sandbox' => $sandbox('GLS'), 'rates' => $rates('PARCEL', 'GLS', 690)]],
    'db_schenker' => ['factory' => 'db_schenker', 'needs' => [], 'options' => ['api_key' => $env('SCHENKER_API_KEY'), 'account_number' => $env('SCHENKER_ACCOUNT'), 'rates' => $rates('SYSTEM', 'DB Schenker System', 2900)]],
    'usps' => ['factory' => 'usps', 'needs' => ['USPS_CLIENT_ID', 'USPS_CLIENT_SECRET'], 'options' => ['client_id' => $env('USPS_CLIENT_ID'), 'client_secret' => $env('USPS_CLIENT_SECRET'), 'crid' => $env('USPS_CRID'), 'mid' => $env('USPS_MID'), 'account' => $env('USPS_EPS_ACCOUNT'), 'sandbox' => $sandbox('USPS')]],
    'royal_mail' => ['factory' => 'royal_mail', 'needs' => ['ROYAL_MAIL_API_KEY'], 'options' => ['api_key' => $env('ROYAL_MAIL_API_KEY'), 'tracking_client_id' => $env('RM_TRACKING_ID'), 'tracking_client_secret' => $env('RM_TRACKING_SECRET'), 'rates' => $rates('TPN01', 'Tracked 24', 550, 'GBP')]],
    'canada_post' => ['factory' => 'canada_post', 'needs' => ['CANADA_POST_USERNAME', 'CANADA_POST_PASSWORD', 'CANADA_POST_CUSTOMER'], 'options' => ['username' => $env('CANADA_POST_USERNAME'), 'password' => $env('CANADA_POST_PASSWORD'), 'customer_number' => $env('CANADA_POST_CUSTOMER'), 'contract_id' => $env('CANADA_POST_CONTRACT'), 'sandbox' => $sandbox('CANADA_POST')]],
    'purolator' => ['factory' => 'purolator', 'needs' => ['PUROLATOR_KEY', 'PUROLATOR_PASSWORD', 'PUROLATOR_ACCOUNT'], 'options' => ['key' => $env('PUROLATOR_KEY'), 'password' => $env('PUROLATOR_PASSWORD'), 'account_number' => $env('PUROLATOR_ACCOUNT'), 'sandbox' => $sandbox('PUROLATOR')]],
    'canpar' => ['factory' => 'canpar', 'needs' => ['CANPAR_USER', 'CANPAR_PASSWORD', 'CANPAR_SHIPPER'], 'options' => ['user_id' => $env('CANPAR_USER'), 'password' => $env('CANPAR_PASSWORD'), 'shipper_number' => $env('CANPAR_SHIPPER'), 'sandbox' => $sandbox('CANPAR')]],
    'auspost' => ['factory' => 'auspost', 'needs' => ['AUSPOST_API_KEY', 'AUSPOST_PASSWORD', 'AUSPOST_ACCOUNT'], 'options' => ['api_key' => $env('AUSPOST_API_KEY'), 'password' => $env('AUSPOST_PASSWORD'), 'account_number' => $env('AUSPOST_ACCOUNT'), 'sandbox' => $sandbox('AUSPOST')]],
    'aramex' => ['factory' => 'aramex', 'needs' => ['ARAMEX_USERNAME', 'ARAMEX_PASSWORD', 'ARAMEX_ACCOUNT', 'ARAMEX_PIN', 'ARAMEX_ENTITY', 'ARAMEX_COUNTRY'], 'options' => ['username' => $env('ARAMEX_USERNAME'), 'password' => $env('ARAMEX_PASSWORD'), 'account_number' => $env('ARAMEX_ACCOUNT'), 'account_pin' => $env('ARAMEX_PIN'), 'account_entity' => $env('ARAMEX_ENTITY'), 'account_country' => $env('ARAMEX_COUNTRY'), 'sandbox' => $sandbox('ARAMEX')]],
    'bluedart' => ['factory' => 'bluedart', 'needs' => ['BLUEDART_CLIENT_ID', 'BLUEDART_CLIENT_SECRET', 'BLUEDART_LOGIN', 'BLUEDART_LICENCE', 'BLUEDART_CUSTOMER'], 'options' => ['client_id' => $env('BLUEDART_CLIENT_ID'), 'client_secret' => $env('BLUEDART_CLIENT_SECRET'), 'login_id' => $env('BLUEDART_LOGIN'), 'licence_key' => $env('BLUEDART_LICENCE'), 'customer_code' => $env('BLUEDART_CUSTOMER'), 'origin_area' => $env('BLUEDART_AREA'), 'sandbox' => $sandbox('BLUEDART')]],
    'dtdc' => ['factory' => 'dtdc', 'needs' => ['DTDC_API_KEY', 'DTDC_CUSTOMER'], 'options' => ['api_key' => $env('DTDC_API_KEY'), 'customer_code' => $env('DTDC_CUSTOMER'), 'tracking_username' => $env('DTDC_TRACK_USER'), 'tracking_password' => $env('DTDC_TRACK_PASSWORD'), 'sandbox' => $sandbox('DTDC'), 'rates' => $rates('B2C PRIORITY', 'DTDC Priority', 25000, 'INR')]],
    'sf_express' => ['factory' => 'sf_express', 'needs' => ['SF_PARTNER_ID', 'SF_CHECKWORD'], 'options' => ['partner_id' => $env('SF_PARTNER_ID'), 'checkword' => $env('SF_CHECKWORD'), 'monthly_card' => $env('SF_MONTHLY_CARD'), 'sandbox' => $sandbox('SF'), 'rates' => $rates('1', '顺丰标快', 1200, 'CNY')]],
    'jdl_express' => ['factory' => 'jdl_express', 'needs' => ['JDL_APP_KEY', 'JDL_APP_SECRET', 'JDL_ACCESS_TOKEN', 'JDL_CUSTOMER'], 'options' => ['app_key' => $env('JDL_APP_KEY'), 'app_secret' => $env('JDL_APP_SECRET'), 'access_token' => $env('JDL_ACCESS_TOKEN'), 'customer_code' => $env('JDL_CUSTOMER'), 'sandbox' => $sandbox('JDL'), 'rates' => $rates('ed-m-0001', '京东特惠送', 1000, 'CNY')]],
    'zto_express' => ['factory' => 'zto_express', 'needs' => ['ZTO_COMPANY_ID', 'ZTO_KEY'], 'options' => ['company_id' => $env('ZTO_COMPANY_ID'), 'key' => $env('ZTO_KEY'), 'partner_code' => $env('ZTO_PARTNER'), 'sandbox' => $sandbox('ZTO'), 'rates' => $rates('standard', '中通快递', 800, 'CNY')]],
    'amazon' => ['factory' => 'amazon', 'needs' => ['AMAZON_LWA_CLIENT_ID', 'AMAZON_LWA_CLIENT_SECRET', 'AMAZON_REFRESH_TOKEN'], 'options' => ['client_id' => $env('AMAZON_LWA_CLIENT_ID'), 'client_secret' => $env('AMAZON_LWA_CLIENT_SECRET'), 'refresh_token' => $env('AMAZON_REFRESH_TOKEN'), 'region' => $env('AMAZON_REGION', 'eu'), 'business_id' => $env('AMAZON_BUSINESS_ID'), 'sandbox' => $sandbox('AMAZON')]],
];
